### ISSUE TITLE
Mise à jour du repo

### ISSUE THREAD

**Issue by Brancieq-Paul** [HerobrineFR/Herobrine.fr-Optimized#106]
### Tâche interne

Mise à jour du repo:

- [x] Ecriture du guide de contribution
    - [x] Préparation de l'environnement
    - [x] Utilisation de Prism
    - [x] Etapes pour une update
    - [x] Explication des liscences
    - [x] ~~Répertoire des configurations changées~~
- [x] Ajouter CI
- [x] Mettre à jour le readme (ajouter le nouveau lien du discord)

**Comment by Raconteur32** [comment]
Considéré comme complet
