### ISSUE TITLE
Respackopts

### ISSUE THREAD

**Issue by Brancieq-Paul** [HerobrineFR/Herobrine.fr-Optimized#27]
### Lien Curseforge

https://www.curseforge.com/minecraft/mc-mods/respackopts

### Distribution curseforge du mod

Autorisée

### Lien Modrinth

https://www.modrinth.com/mod/respackopts

### Source ou autre lien

https://gitlab.com/jfmods/respackopts

### Description

Permet d'intégrer des options de resource pack

### Pourquoi sur HB ?

Permettrais d'intégrer les packs de saisons et autres variantes directement dans le pack principal et de juste devoir changer d'options pour changer de saison.

### Points négatifs

Demanderais d'adapter les packs HB pour avoir des options

### Autre

Suivre l'issue de FO: https://github.com/Fabulously-Optimized/fabulously-optimized/issues/210

**Comment by Raconteur32** [comment]
Déjà intégré pour le pack lanterne. Devrait être plus intégré dans #104
