### ISSUE TITLE
Inclure les licenses d'utilisation des mods en dur dans le .mrpack

### ISSUE THREAD

**Issue by Brancieq-Paul** [HerobrineFR/Herobrine.fr-Optimized#89]
### Tâche interne

Tout est écrit. ChatGPT explique bien les conditions pour chaque license. l'utiliser pour savoir quelles sont les conditions de redistributions et les inclure dans le .mrpack

**Comment by Raconteur32** [comment]
Les licences sont incluses, elles seront peut-être juste à changer de place à l'avenir
